// <auto-generated/>
#pragma warning disable
#nullable enable annotations

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel;

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// This attribute is used to mark extension members and associate them with a specific marker type (which provides detailed information about an extension block and its receiver parameter).
    /// This attribute should not be used by developers in source code.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsable(EditorBrowsableState.Never)]
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class |
        global::System.AttributeTargets.Struct |
        global::System.AttributeTargets.Enum |
        global::System.AttributeTargets.Method |
        global::System.AttributeTargets.Property |
        global::System.AttributeTargets.Field |
        global::System.AttributeTargets.Event |
        global::System.AttributeTargets.Interface |
        global::System.AttributeTargets.Delegate,
        Inherited = false)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Microsoft.CodeAnalysis.Embedded]
    internal sealed class ExtensionMarkerAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance of the <see cref="global::System.Runtime.CompilerServices.ExtensionMarkerAttribute"/> class.</summary>
        /// <param name="name">The name of the marker type this extension member is associated with.</param>
        public ExtensionMarkerAttribute(string name)
            => Name = name;

        /// <summary>The name of the marker type this extension member is associated with.</summary>
        public string Name { get; }
    }
}