// <auto-generated/>
#pragma warning disable
#nullable enable annotations

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System
{
    /// <summary>Provides downlevel polyfills for static methods on Exception-derived types.</summary>
    internal static class ExceptionPolyfills
    {
        extension(global::System.ArgumentNullException)
        {
            public static void ThrowIfNull(
                [global::System.Diagnostics.CodeAnalysis.NotNull] object? argument,
                [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(argument))] string? paramName = null
            )
            {
                if (argument is null)
                {
                    ThrowArgumentNullException(paramName);
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
        private static void ThrowArgumentNullException(string? paramName) =>
            throw new global::System.ArgumentNullException(paramName);

        extension(global::System.ObjectDisposedException)
        {
            public static void ThrowIf([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIf(true)] bool condition, object instance)
            {
                if (condition)
                {
                    ThrowObjectDisposedException(instance);
                }
            }

            public static void ThrowIf([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIf(true)] bool condition, global::System.Type type)
            {
                if (condition)
                {
                    ThrowObjectDisposedException(type);
                }
            }
        }

        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
        private static void ThrowObjectDisposedException(object? instance)
        {
            throw new global::System.ObjectDisposedException(instance?.GetType().FullName);
        }

        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
        private static void ThrowObjectDisposedException(global::System.Type? type)
        {
            throw new global::System.ObjectDisposedException(type?.FullName);
        }
    }
}