// <auto-generated/>
#pragma warning disable
#nullable enable annotations

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Defines the contract for union types, providing access to the underlying value.
    /// </summary>
    internal interface IUnion
    {
        /// <summary>
        /// Gets the underlying value of the union.
        /// </summary>
        object? Value { get; }
    }
}
