namespace PolySharp.SourceGenerators.Models;

/// <summary>
/// Fixups for <see cref="AvailableType"/>.
/// </summary>
internal enum AvailableTypeFixup
{
    /// <summary>
    /// No fixup is needed.
    /// </summary>
    None,

    /// <summary>
    /// Remove all <c>[MethodImpl]</c> attributes.
    /// </summary>
    RemoveMethodImplAttributes,

    /// <summary>
    /// Skips generating <c>[UnmanagedCallersOnly]</c> if a type alias is requested, as the target project already has
    /// an accessible version of the aliased type (ie. generated by PolySharp in a referenced upstream project from this).
    /// </summary>
    BypassUnmanagedCallersOnlyAttributeTypeIfAliasRequested
}
