// <auto-generated/>
#pragma warning disable
#nullable enable annotations

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Runtime.InteropServices
{
    /// <summary>
    /// Specifies that the P/Invoke marked with this attribute should be linked in as a WASM import.
    /// </summary>
    /// <remarks>
    /// See https://webassembly.github.io/spec/core/syntax/modules.html#imports.
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("MULTI_TARGETING_SUPPORT_ATTRIBUTES")]
    internal sealed class WasmImportLinkageAttribute : global::System.Attribute
    {
        /// <summary>
        /// Instance constructor.
        /// </summary>
        public WasmImportLinkageAttribute() { }
    }
}