// <auto-generated/>
#pragma warning disable
#nullable enable annotations

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Specifies the kind of target to which an <see cref="global::System.Runtime.CompilerServices.UnsafeAccessorAttribute" /> is providing access.
    /// </summary>
    [global::Microsoft.CodeAnalysis.Embedded]
    internal enum UnsafeAccessorKind
    {
        /// <summary>
        /// Provide access to a constructor.
        /// </summary>
        Constructor,

        /// <summary>
        /// Provide access to a method.
        /// </summary>
        Method,

        /// <summary>
        /// Provide access to a static method.
        /// </summary>
        StaticMethod,

        /// <summary>
        /// Provide access to a field.
        /// </summary>
        Field,

        /// <summary>
        /// Provide access to a static field.
        /// </summary>
        StaticField
    }
}