// <auto-generated/>
#pragma warning disable
#nullable enable annotations

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Runtime.CompilerServices2
{
    /// <summary>
    /// Indicates that the instance's storage is sequentially replicated "length" times.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This attribute can be used to annotate a <see langword="struct"/> type with a single field.
    /// The runtime will replicate that field in the actual type layout as many times as is specified.
    /// </para>
    /// <para>
    /// Here's an example of how an inline array type with 8 <see cref="float"/> values can be declared:
    /// <code lang="csharp">
    /// [InlineArray(8)]
    /// struct Float8InlineArray
    /// {
    ///     private float _value;
    /// }
    /// </code>
    /// </para>
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.Conditional("MULTI_TARGETING_SUPPORT_ATTRIBUTES")]
    internal sealed class InlineArrayAttribute : global::System.Attribute
    {
        /// <summary>Creates a new <see cref="global::System.Runtime.CompilerServices2.InlineArrayAttribute"/> instance with the specified length.</summary>
        /// <param name="length">The number of sequential fields to replicate in the inline array type.</param>
        public InlineArrayAttribute(int length)
        {
            Length = length;
        }

        /// <summary>Gets the number of sequential fields to replicate in the inline array type.</summary>
        public int Length { get; }
    }
}